# -*- coding: utf-8 -*-
"""loop control.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GN4lUDEn0rq6A8xAWMunw4HOxRB4LtO7
"""

#1. print all natural numbers from 1 to n. - using while loop

n = int(input('Enter a natural number: '))
i = 1
while i <= n:
    print(i, end='')
    i += 1

#2. Write a Python program to print all natural numbers in reverse
# (from n to 1). - using while loop

n = int(input('Enter a natural number: '))
while n > 0:
  print(n, end='')
  n-=1

ascii

#3.  print all alphabets from a to z. - using while loop
a = ord('A')
z = ord('Z')
while a <= z:
  print(chr(a), end='')
  a += 1

#4. print all even numbers between 1 to 100. - using while loop

i = 1
while i<=100:
  if i%2==0:
    print(i,end='')
  i+=1

#5. print all odd number between 1 to 100.
#while loop
i = 1
while i<=100:
  if i%2 != 0:
    print(i, end='')
  i+=1

#for loop
for i in range(1, 100):
  if i%2 != 0:
    print(i, end='')

[i for i in range(1,100) if i%2 != 0]

#6. find sum of all natural numbers between 1 to n.
#for loop
n = int(input('Enter number: '))
Total = 0
for i in range(1, n+1):
  Total += i
print(('total sum of 1 to'), n,'=', Total)

#while loop
n = int(input('Enter a number: '))
i=1
Total = 0
while i<=n:
    Total += i
    i+=1
print('Total of 1 to', n, 'is', Total)

#7.  find sum of all even numbers between 1 to n.
#while loop
n = int(input('Enter n: '))
i = 1
total = 0
while i< n :
  i+=1
  if i%2 == 0:
    print(i)
    total += i
print('Sum of even number in between 1 to',n,'is',total)

#for loop
n = int(input('Enter n: '))
total = 0
for i in range(1,n):
  if i%2 == 0:
    print(i)
    total = total+i
print('sum: 10', total)

#8. find sum of all odd numbers between 1 to n.
# while loop
n = int(input('enter n: '))
i = 1
total = 0
while i < n:
  i+=1
  if i%2!=0:
    print(i)
    total += i
print('Sum of odd number is', total)

#for loop
n = int(input('entrr n: '))
total = 0
for i in range(1,n):
  if i%2 != 0:
    print(i)
    total += i
print('sum of odd number is', total)

#10. print multiplication table of any number. Take user input.
#list comprehension
n = int(input('enter number: '))
[i*n for i in range(1,11)]

#for loop

for i in range(0,11):
  i = i*n
  print(i, end='')
#while loop
j=0
while n<=10:
  j+=1
  j = j*n
  print(j)

#1. Basic Counting from 1 to 5
i = 1
while i<=5:
  print(i)
  i+=1

#2. Reverse Counting from 10 to 1
i = 10
while i >= 1:
  print(i,end='')
  i -=1

#3. Sum of First 10 Natural Numbers
i=1
total = 0
while i<=10:
  total = total+i
  i+=1
print('Sum of 1st 10 natural no.is',total)

#4. Multiplication Table
n = int(input('enter a number u want multiplication table: '))
i = 0
while i <=9:
  i+=1
  j = n*i
  print((n), 'x', (i), '=', j)

#5. Password Input Until Correct
import getpass
password = getpass.getpass()
Entered_pass = input('enter password: ')
while Entered_pass != password:
  print('wrong paswrod')
  Entered_pass = input('Enter again: ')
print('Succesfully Login.')

#6. Guess the number game
secret = 6969
i = 0
while i != secret:
  print("Try again")
  i = int(input('Choose a number: '))

print('Correct guess', i)

#7. Even Numbers from 2 to 20
i = 0
while i < 20:
  i += 2
  print(i)

#8. Factorial of a Number
n = int(input('Enter a number: '))
fact = 1
while n>0:
  fact = fact*n
  n-=1
print('Factorial of',(n),'is',fact)

#9. Menu-Driven Program
choice = int(input('Enter choice: '))
while choice != 4:
  print('1. Addition')
  print('2. Subtraction')
  print('3. Multiplication')
  print('4. Division')
  choice = int(input('Enter choice: '))
  if choice == 1:
    print('you choose addition')
  elif choice == 2:
    print('you choose Subtraction')
  elif choice == 3:
    print('you choose multiplication')
  elif choice == 4:
    print('you choose Division')
else:
    print('wrong input')

n = int(input('Enter n:'))

#1. 1. Create a List of Squares

[i**2 for i in range(1,n)]

#2. Filter Even Numbers from a List
[i for i in range(0,n) if i%2 ==0]

#3. Convert Words to Uppercase
z = [chr(i) for i in range(ord('a'), ord('z')+1)]
[i.upper() for i in z]

#4. Find Length of Each Word
[len(i) for i in z]

#5. Select Words Longer Than 4 Characters
words = [
    "cat",
    "house",
    "tree",
    "python",
    "book",
    "elephant",
    "sun",
    "computer",
    "code",
    "banana"
]
[i for i in words if len(i)>=4]

from os import replace
#6. Create a List Using if-else in List Comprehension
l1 = [word if len(word)>=4 else '' for word in words]
l1

#7. Extract First Letter of Each Word
[word[0] for word in words]

#8. Remove Empty Strings from a List
[word for word in l1 if word != '']

#9. Flatten a Nested List
nested_list = [[1, 2, 3], [4, 5], [6, 7, 8]]
[i for sublist in nested_list for i in sublist]

#10 Create Pairs from Two Lists
[(i,j) for i,j in zip(z,words)]

#11. Convert Celsius temprature into farhenite
celsius = [0, 10, 20, 30, 40]
[(temprature*9/5)+32 for temprature in celsius]

#12. Find Numbers Common in Two list
list1 = [1, 2, 3, 4, 5, 6]
list2 = [4, 5, 6, 7, 8, 9]

[num for num in list1 if  list2]

#12. Find Numbers Common in Two list
list1 = [1, 2, 3, 4, 5, 6]
list2 = [4, 5, 6, 7, 8, 9]

[num for num in list1 if num in list2]

nested_list = [[1, 2, 3], [4, 5], [6, 7, 8]]
[i for sublist in nested_list for i in sublist]

n = int(input('enter n: '))

#1. Get Squares of Only Even Numbers
[num**2 for num in range(0, n) if num%2 == 0]

#2. Remove Vowels from a String
name = ('Jayesh')
vowels = ('aeiouAEIOU')
m = "".join([i for i in name if i in vowels])
m

#3. Find Common Elements Between Two Lists
list3 = [1, 2, 3, 4, 5, 6]
list4 = [4, 5, 6, 7, 8, 9]
[i for i in list3 if i in list4]

#4. Flatten a 2D list
data = [[10, 20], [30, 40], [50, 60]]
[i for i in data for i in i]

#5. Find Words Starting with a Specific Letter
words = ["Python", "Java", "Pandas", "SQL", "PowerBI"]
[i for i in words if i.startswith('P')]

#6. Convert List of Strings to Integers
values = ["10", "20", "30", "40"]
[int(i) for i in values]

#7. Replace Negative Numbers with Zero
numbers = [5, -2, 8, -7, 3]
[num if num>0 else(0) for num in numbers]

#8. Extract Digits from a String
text = "A12B45C7"
[ i for i in text if i.isdigit() ]

#9. Transpose a Matrix
matrix = [[1, 2, 3], [4, 5, 6]]
[(i,j) for i, j in matrix ]

#10. Find Prime Numbers from a List
numbers = [1, 2, 2, 3, 4, 4, 5]
[num for num in numbers if num>1 and all(num%i != 0 for i in range(2,num) )]

l

list1 = [1, 2, 3, 4, 5, 6,11,23,45]
list2 = [4, 5, 6, 7, 8, 9]
[i for j in [list1,list2] for i in j]

[i for i in zip(list1,list2)]

[(1, 4), (2, 5), (3, 6), (4, 7), (5, 8), (6, 9)]
[(1, 4), (2, 5), (3, 6), (4, 7), (5, 8), (6, 9)]